import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { Provider } from "~/components/provider";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={`${GeistSans.variable}`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
